### ISSUE TITLE
Add a file with the name and roles of all contributors of the project

### ISSUE THREAD

**Issue by estefaniaramirezmnt** [estefaniaramirezmnt/github-planning-pipeline-test#2]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A md file with a table with the names and roles of the developers in this project

**Describe alternatives you've considered**
It can have other information too, like the country

**Additional context**
N/A

**Comment by juanlu-sanz** [comment]
Closed on #3
